SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mar 19, 2020 7:41:41 PM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
Mar 19, 2020 7:41:41 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {5.2.13.Final}
Mar 19, 2020 7:41:41 PM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
Mar 19, 2020 7:41:41 PM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
Mar 19, 2020 7:41:42 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.DerbyTenSixDialect
Mar 19, 2020 7:41:43 PM org.hibernate.hql.internal.QueryTranslatorFactoryInitiator initiateService
INFO: HHH000397: Using ASTQueryTranslatorFactory
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: Database 'memory:testdb' not created, connection made to existing database instead.
Mar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarning
WARN: SQL Warning Code: 10000, SQLState: 01J01
Mar 19, 2020 7:41:44 PM org.hibernHibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, mMar 19, 2020 7:41:44 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler logWarninHibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
   Mar 19, 2020 7:41:44 PHibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
    identity_val_local()
Hibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
    identity_val_local()
Hibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
    identity_val_local()
Hibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
    identity_val_local()
Hibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
    identity_val_local()
Hibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
    identity_val_local()
Hibernate: 
    /* insert com.javapro.costs.model.Purchase
        */ insert 
        into
            purchase
            (id, category, comment, created_date, money) 
        values
            (default, ?, ?, ?, ?)
Hibernate: 
    
values
    identity_val_local()
Hibernate: 
    select
        purchase0_.id as id1_0_0_,
        purchase0_.category as category2_0_0_,
        purchase0_.comment as comment3_0_0_,
        purchase0_.created_date as created_4_0_0_,
        purchase0_.money as money5_0_0_ 
    from
        purchase purchase0_ 
    where
        purchase0_.id=?
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.076 sec <<< FAILURE! - in com.javapro.costs.service.PurchaseServiceTest
get(com.javapro.costs.service.PurchaseServiceTest)  Time elapsed: 0.092 sec  <<< ERROR!
com.javapro.costs.exception.NotFoundException: Can't find purchase with id=1
	at com.javapro.costs.service.PurchaseServiceImpl.get(PurchaseServiceImpl.java:22)
	at com.javapro.costs.service.PurchaseServiceTest.get(PurchaseServiceTest.java:41)


Results :

Tests in error: 
  PurchaseServiceTest.get:41 Â» NotFound Can't find purchase with id=1

Tests run: 5, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.764 s
[INFO] Finished at: 2020-03-19T19:41:45+01:00
[INFO] Final Memory: 14M/67M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project costs: There are test failures.
[ERROR] 
[ERROR] Please refer to /scratch/dginelli/workspace/repairnator-repairnator-experiments-unlimit1984-costs-369859631-20180422-231435-firstCommit/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project costs: There are test failures.

Please refer to /scratch/dginelli/workspace/repairnator-repairnator-experiments-unlimit1984-costs-369859631-20180422-231435-firstCommit/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /scratch/dginelli/workspace/repairnator-repairnator-experiments-unlimit1984-costs-369859631-20180422-231435-firstCommit/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:195)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:861)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:729)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
