{
  "totalNumberSkippingTests": 31,
  "bugType": "only_fail",
  "totalNumberErroringTests": 1,
  "repo": "CESNET/perun",
  "failingModule": "/root/workspace/CESNET/perun/366488763/perun-core",
  "hostname": "spirals-vortex.lille.inria.fr",
  "totalNumberFailingTests": 0,
  "error-types": [
    "cz.metacentrum.perun.core.api.exceptions.InternalErrorException"
  ],
  "totalNumberRunningTests": 1545,
  "failing-test-cases": [
    {
      "className": "cz.metacentrum.perun.core.entry.ResourcesManagerEntryIntegrationTest",
      "failingMethods": [],
      "erroringMethods": [
        "cz.metacentrum.perun.core.entry.ResourcesManagerEntryIntegrationTest#copyResourceDifferentVO"
      ],
      "failures": [
        {
          "failureName": "cz.metacentrum.perun.core.api.exceptions.InternalErrorException",
          "failureDetail": "Error 162c4569220: Resources are not from the same VO.",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    }
  ]
}